# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171102_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m'),
        ),
    ]
