# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20171107_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',)},
        ),
    ]
