# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-08 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0005_auto_20171107_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_mode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
