# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0007_auto_20171113_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snippet',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='snippets_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snippet',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='snippets_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
